######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 4 09:08:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h
SOURCES += imageviewer.cpp main.cpp
