######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 10 22:23:45 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snakeboard.h snakewindow.h
SOURCES += computerGo.cpp main.cpp snakeboard.cpp snakewindow.cpp
