######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 8 16:16:22 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snakeboard.h snakewindow.h
SOURCES += main.cpp snakeboard.cpp snakewindow.cpp
