######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 11 19:57:56 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snakeboard.h snakewindow.h
SOURCES += computerGo.cpp main.cpp snakeboard.cpp snakewindow.cpp
