######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 24 22:47:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clockthread.h
SOURCES += clockthread.cpp main.cpp
