######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 1 20:26:24 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += button.h calculator.h
SOURCES += button.cpp calculator.cpp main.cpp
