######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 6 20:59:20 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h wigglywidget.h
SOURCES += dialog.cpp main.cpp wigglywidget.cpp
