######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 7 21:01:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += renderarea.h window.h
SOURCES += main.cpp renderarea.cpp window.cpp
RESOURCES += basicdrawing.qrc
