######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 7 19:30:15 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tetrixboard.h tetrixpiece.h tetrixwindow.h
SOURCES += main.cpp tetrixboard.cpp tetrixpiece.cpp tetrixwindow.cpp
