######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 26 20:43:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += block.h renderthread.h window.h
SOURCES += block.cpp main.cpp renderthread.cpp window.cpp
