######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 8 10:06:57 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += analogclock.h
SOURCES += analogclock.cpp main.cpp
