######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 6 10:08:30 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ActionArea.h CalThread.h fun.h PlayArea.h
SOURCES += ActionArea.cpp CalThread.cpp computerGo.cpp main.cpp PlayArea.cpp
