######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 2 20:41:02 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalThread.h fun.h PlayArea.h
SOURCES += CalThread.cpp computerGo.cpp main.cpp PlayArea.cpp
