######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 9 23:10:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PlayArea.h
SOURCES += main.cpp PlayArea.cpp
