######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 23 10:34:14 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += audioinput.h
SOURCES += audioinput.cpp main.cpp
QT += multimedia
