######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 20 19:42:54 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += norwegianwoodstyle.h widgetgallery.h
SOURCES += main.cpp norwegianwoodstyle.cpp widgetgallery.cpp
RESOURCES += styles.qrc
